# Home Assistant Add-on Build Configuration
# Uses pre-built images from GitHub Container Registry (GHCR)
# Images are built with correct architecture using GitHub Actions + Docker Buildx

# IMPORTANT: This uses pre-built images to avoid architecture mismatch issues
# Images are built automatically via GitHub Actions workflow
# See: .github/workflows/build-addon.yml

# Pull pre-built image from GHCR (built by GitHub Actions)
image: "ghcr.io/dodoooh/hasync-addon:amd64-{version}"

# Fallback: Local build configuration (only used if image pull fails)
# Uncomment to force local rebuild:
# build_from:
#   amd64: "ghcr.io/home-assistant/amd64-base:3.15"
#   armhf: "ghcr.io/home-assistant/armhf-base:3.15"
#   armv7: "ghcr.io/home-assistant/armv7-base:3.15"
#   aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
#   i386: "ghcr.io/home-assistant/i386-base:3.15"

args:
  TEMPIO_VERSION: "2021.09.0"
